---
title: "wk6"
format: html
editor_options: 
  chunk_output_type: inline
---

## Set up

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(sf)
library(terra)
library(tmap)
library(tmaptools)
```

```{r}
# Set directory for folder
pre_fire_dir <- here::here("data", "LC80340322016189-SC20170128091153")

# Create a list of all images that have the extension .tif and contain the word band
pre_fire_bands <- list.files(pre_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
pre_fire_rast <- rast(pre_fire_bands)

# Read mask raster
pre_mask <- rast(here::here("data", "LC80340322016189-SC20170128091153", "LC80340322016189LGN00_cfmask_crop.tif"))
```

```{r}
# Set directory for folder
post_fire_dir <- here::here("data", "LC80340322016205-SC20170127160728")

# Create a list of all images that have the extension .tif and contain the word band
post_fire_bands <- list.files(post_fire_dir,
                             pattern = glob2rx("*band*.tif$"),
                             full.names = TRUE)
# Create a raster stack
post_fire_rast <- rast(post_fire_bands)

# Read mask raster
post_mask <- rast(here::here("data", "LC80340322016205-SC20170127160728", "LC80340322016205LGN00_cfmask_crop.tif"))
```

```{r}
# Define a function to calculate the normalized burn ratio (NBR)
nbr_fun <- function(nir, swir2) {
  
    (nir - swir2) / (nir + swir2)
  
}
```

## Rename and mask the bands

```{r}
# Rename bands
bands <- c("Aerosol", "Blue", "Green", "Red", "NIR", "SWIR1", "SWIR2")
names(pre_fire_rast) <- bands
names(post_fire_rast) <- bands
```

```{r}
# Set all cells with values greater than 0 to NA
pre_mask[pre_mask > 0] <- NA

# Subset raster based on mask
pre_fire_rast <- mask(pre_fire_rast, mask = pre_mask)

# View raster
plot(pre_fire_rast)
```

```{r}
# Set all cells with values greater than 0 to NA
post_mask[post_mask > 0] <- NA

# Subset raster based on mask
post_fire_rast <- mask(post_fire_rast, mask = post_mask)

# View raster
plot(post_fire_rast)
```

## Plot true and false color composites

```{r}
plotRGB(pre_fire_rast, r = 4, g = 3, b = 2, 
        stretch = "lin", colNA = "black")
```

```{r}
plotRGB(post_fire_rast, r = 4, g = 3, b = 2, 
        stretch = "lin", colNA = "black")
```

```{r}
plotRGB(pre_fire_rast, r = 7, g = 5, b = 3,
        stretch = "lin", colNA = "black")
```

```{r}
plotRGB(post_fire_rast, r = 7, g = 5, b = 3,
        stretch = "lin", colNA = "black")
```

## Calculate the normalized burn ratio (NBR)

```{r}
pre_nbr_rast <- terra::lapp(pre_fire_rast[[c(5, 7)]], fun = nbr_fun)

plot(pre_nbr_rast, main = "Cold Springs Pre-Fire NBR", colNA = "black")
```
```{r}
post_nbr_rast <- terra::lapp(post_fire_rast[[c(5, 7)]], fun = nbr_fun)

plot(post_nbr_rast, main = "Cold Springs Post-Fire NBR", colNA = "black")
```

## Calculate and plot difference NBR

```{r}
# Difference in NBR
d_nbr <- pre_nbr_rast - post_nbr_rast

tm_shape(d_nbr) +
  tm_raster(style = "equal", n = 6,
            palette = brewer.pal(4, "Set3"),
            title = "Difference NBR (dNBR)", colorNA = "black") +
  tm_layout(legend.outside = TRUE)
```

