---
title: "wk1"
format: html
editor_options: 
  chunk_output_type: inline
---

```{r}
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
```

```{r}
ei_points <- st_read(here("data", "easter_island", "ei_points.gpkg")) |> 
  filter(type == "volcano")
ei_elev <- read_stars(here("data", "easter_island", "ei_elev.tif"))
ei_borders <- st_read(here("data", "easter_island", "ei_border.gpkg"))
ei_roads <- st_read(here("data", "easter_island", "ei_roads.gpkg"))
```

```{r}
tm_shape(ei_borders) +
  tm_borders() +
  tm_layout(main.title = "Easter Island")
```

```{r}
ei_map <- tm_shape(ei_elev) +
  tm_graticules() +
  tm_raster(col.scale = tm_scale_continuous(values = "-rd_yl_gn"),
            col.legend = tm_legend("Elevation (m asl)")) +
tm_shape(ei_borders) +
  tm_borders() +
tm_shape(ei_roads) +
  tm_lines() +
tm_shape(ei_points) +
  tm_symbols(shape = 24,
             size = "elevation",
             size.legend = tm_legend("Volcanoes (m asl)")) +
  tm_compass(position = c("right", "top")) +
  tm_scalebar() +
  tm_layout(main.title = "Easter Island")

ei_map
```

```{r}
tmap_mode("view")

ei_map
```

=======
tm_shape()
```
>>>>>>> 1ab5e894a9dadfc9c48a7fab4c8d1ef032e81a8d
